[default]
# Porta na qual o servidor embutida irá executar
port = 8000
# Caminho para o diretório com os templates .tera
template_dir = "templates"

[default.databases.database]
# String de conexão do postgres
# Mais info: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING
url = "postgresql:///misterio?user=misterio&host=/var/run/postgresql"
